name: test

on:
  push:
  pull_request:

jobs:
  cargo:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.90"
          components: clippy
      - name: тести
        run: cargo test --workspace
      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
